version: 2.1

jobs:

  build:
    docker:
      - image: docker:17.05.0-ce-git

workflows:
  version: 2
  flow:
    jobs:
    build:
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: install dependencies
            command: apk add --update alpine-sdk
        - run:
            name: build docker image
            command: make docker-build
        - run:
            name: login to docker.io
            command: make docker-login
        - run:
            name: push image to docker.io
            command: make docker-push
        - run:
            name: log out of docker.io
            command: make docker-logout
